
TYPE
	MD_Profiler_Step : 
		(
		MD_PROF_GET_STATE := 0,
		MD_PROF_STOPPING,
		MD_PROF_DEINSTALLING,
		MD_PROF_CHECK_DEINSTALLED,
		MD_PROF_INSTALLING,
		MD_PROF_STARTING,
		MD_PROF_CHECK_RUNNING,
		MD_PROF_RUNNING,
		MD_PROF_ARCH_STOP,
		MD_PROF_ARCH_CREATE,
		MD_PROF_ERROR
		);
END_TYPE
